name: Release
run-name: Process Release on ${{ github.event.workflow_run.head_branch }} `${{ github.event.workflow_run.head_sha }}`
on:
  workflow_run:
    workflows: ["Go"]
    branches: [main]
    types:
      - completed

concurrency:
  group: release-please-${{ github.ref }}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v4

  fail-release:
    name: Fail Release
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'failure'

    steps:
      - run: |
          echo "::error ::Cannot release unless 'Go' workflow suceeds!"
          exit 1
